// Small ISO 639-2 (and a few -1) code -> friendly name lookup. Falls back to the
// raw code itself when we don't recognise it (matches how most media players behave).
const LANGUAGE_NAMES = {
  eng: "English",
  en: "English",
  ara: "Arabic",
  ar: "Arabic",
  cze: "Czech",
  ces: "Czech",
  cs: "Czech",
  ger: "German",
  deu: "German",
  de: "German",
  spa: "Spanish",
  es: "Spanish",
  fre: "French",
  fra: "French",
  fr: "French",
  hin: "Hindi",
  hi: "Hindi",
  hun: "Hungarian",
  hu: "Hungarian",
  ind: "Indonesian",
  id: "Indonesian",
  ita: "Italian",
  it: "Italian",
  jpn: "Japanese",
  ja: "Japanese",
  kor: "Korean",
  ko: "Korean",
  pol: "Polish",
  pl: "Polish",
  por: "Portuguese",
  pt: "Portuguese",
  rus: "Russian",
  ru: "Russian",
  chi: "Chinese",
  zho: "Chinese",
  zh: "Chinese",
  tur: "Turkish",
  tr: "Turkish",
  vie: "Vietnamese",
  vi: "Vietnamese",
  tha: "Thai",
  th: "Thai",
  dut: "Dutch",
  nld: "Dutch",
  nl: "Dutch",
  swe: "Swedish",
  sv: "Swedish",
  nor: "Norwegian",
  no: "Norwegian",
  dan: "Danish",
  da: "Danish",
  fin: "Finnish",
  fi: "Finnish",
  gre: "Greek",
  ell: "Greek",
  el: "Greek",
  heb: "Hebrew",
  he: "Hebrew",
  ben: "Bengali",
  bn: "Bengali",
  ukr: "Ukrainian",
  uk: "Ukrainian",
  ron: "Romanian",
  rum: "Romanian",
  ro: "Romanian",
  und: null,

  // Rest of Whisper's 99-language set (see subtitle/transcribe.js
  // TRANSCRIBE_LANGUAGES) — filled in so a language picked up by auto-detect
  // always gets a friendly name here too, not just the raw 2-letter code.
  af: "Afrikaans",
  sq: "Albanian",
  am: "Amharic",
  hy: "Armenian",
  as: "Assamese",
  az: "Azerbaijani",
  ba: "Bashkir",
  eu: "Basque",
  be: "Belarusian",
  bs: "Bosnian",
  br: "Breton",
  bul: "Bulgarian",
  bg: "Bulgarian",
  cat: "Catalan",
  ca: "Catalan",
  hrv: "Croatian",
  hr: "Croatian",
  est: "Estonian",
  et: "Estonian",
  fo: "Faroese",
  glg: "Galician",
  gl: "Galician",
  kat: "Georgian",
  ka: "Georgian",
  guj: "Gujarati",
  gu: "Gujarati",
  hat: "Haitian Creole",
  ht: "Haitian Creole",
  hau: "Hausa",
  ha: "Hausa",
  haw: "Hawaiian",
  isl: "Icelandic",
  is: "Icelandic",
  jav: "Javanese",
  jw: "Javanese",
  kan: "Kannada",
  kn: "Kannada",
  kaz: "Kazakh",
  kk: "Kazakh",
  khm: "Khmer",
  km: "Khmer",
  lao: "Lao",
  lo: "Lao",
  lat: "Latin",
  la: "Latin",
  lav: "Latvian",
  lv: "Latvian",
  lin: "Lingala",
  ln: "Lingala",
  lit: "Lithuanian",
  lt: "Lithuanian",
  ltz: "Luxembourgish",
  lb: "Luxembourgish",
  mac: "Macedonian",
  mkd: "Macedonian",
  mk: "Macedonian",
  mlg: "Malagasy",
  mg: "Malagasy",
  msa: "Malay",
  ms: "Malay",
  mal: "Malayalam",
  ml: "Malayalam",
  mlt: "Maltese",
  mt: "Maltese",
  mao: "Maori",
  mi: "Maori",
  mar: "Marathi",
  mr: "Marathi",
  mon: "Mongolian",
  mn: "Mongolian",
  mya: "Burmese",
  my: "Burmese",
  nep: "Nepali",
  ne: "Nepali",
  nno: "Norwegian Nynorsk",
  nn: "Norwegian Nynorsk",
  oci: "Occitan",
  oc: "Occitan",
  pus: "Pashto",
  ps: "Pashto",
  per: "Persian",
  fas: "Persian",
  fa: "Persian",
  pan: "Punjabi",
  pa: "Punjabi",
  san: "Sanskrit",
  sa: "Sanskrit",
  srp: "Serbian",
  sr: "Serbian",
  sna: "Shona",
  sn: "Shona",
  snd: "Sindhi",
  sd: "Sindhi",
  sin: "Sinhala",
  si: "Sinhala",
  slo: "Slovak",
  slk: "Slovak",
  sk: "Slovak",
  slv: "Slovenian",
  sl: "Slovenian",
  som: "Somali",
  so: "Somali",
  sun: "Sundanese",
  su: "Sundanese",
  swa: "Swahili",
  sw: "Swahili",
  tgl: "Tagalog",
  tl: "Tagalog",
  tgk: "Tajik",
  tg: "Tajik",
  tam: "Tamil",
  ta: "Tamil",
  tat: "Tatar",
  tt: "Tatar",
  tel: "Telugu",
  te: "Telugu",
  bod: "Tibetan",
  bo: "Tibetan",
  tuk: "Turkmen",
  tk: "Turkmen",
  urd: "Urdu",
  ur: "Urdu",
  uzb: "Uzbek",
  uz: "Uzbek",
  cym: "Welsh",
  cy: "Welsh",
  yid: "Yiddish",
  yi: "Yiddish",
  yor: "Yoruba",
  yo: "Yoruba",
};

/** Friendly name for a 2/3-letter language code, or the raw code if unknown. */
export function languageName(code) {
  if (!code) return null;
  const key = code.toLowerCase();
  if (key in LANGUAGE_NAMES) return LANGUAGE_NAMES[key];
  return code;
}

/** Full row label, e.g. "English (eng)" or just "ben" when we don't know the name. */
export function languageLabel(code) {
  const name = languageName(code);
  if (!code) return "Unknown language";
  if (!name || name.toLowerCase() === code.toLowerCase()) return code;
  return `${name} (${code})`;
}
